main: main.cpp
	g++ -I /usr/include/eigen3/ accelGCorrection.cpp BangBang.cpp baro_acc_kf.cpp OPI_IMU.cpp brushless.cpp EMAFilter.cpp Gimbal.cpp gyro_ekf.cpp Kalman_Filter_Tran_Vel_Est.cpp Madgwick_Filter.cpp MotorControl.cpp optical_ekf.cpp PID.cpp servo.cpp tripleBallGrabber.cpp main.cpp -lwiringPi -lm -o test
