name: Close and Open Milestones
on:
    schedule:
        - cron: "0 22 * * 4" # Every Thursday at 10 PM

jobs:
    close-and-open-milestones:
        runs-on: self-hosted

        steps:
            - name: Checkout repository
                uses: actions/checkout@v2

            - name: Close old and completed milestones
                run: |
                    # Close completed milestones
                    # Replace <repository> with your repository name
                    # Replace <token> with a personal access token with the `repo` scope
                    curl -X PATCH \
                        -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/SWAMP-Blimps/CatchingBlimp/milestones?state=all \
                        -d '{"state": "closed"}'

            - name: Open new milestone
                run: |
                    # Open a new milestone for two weeks from now
                    # Replace <repository> with your repository name
                    # Replace <token> with a personal access token with the `repo` scope
                    curl -X POST \
                        -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/SWAMP-Blimps/CatchingBlimp/milestones \
                        -d '{"title": "New Milestone", "state": "open", "due_on": "$(date -v+2w -u +%Y-%m-%dT%H:%M:%SZ)"}'
