name: Manage Milestones

on:
  schedule:
    - cron: '0 3 * * 5' # Runs at 03:00 UTC on Fridays (10:00 PM EST on Thursdays)
  workflow_dispatch: # Allows manual trigger

jobs:
    delete-and-create-milestone:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Delete Complete Milestones
              run: |
                    # Get all open milestones
                    open_milestones=$(curl -s -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" \
                        "https://api.github.com/repos/SWAMP-Blimps/CatchingBlimp/milestones?state=open")

                    # Loop through each milestone
                    for milestone in $(echo "$open_milestones" | jq -r '.[] | @base64'); do
                        milestone_name=$(echo "$milestone" | base64 --decode | jq -r '.title')
                        milestone_due_date=$(echo "$milestone" | base64 --decode | jq -r '.due_on')

                        # Check if milestone is not "long-term" and due date is in the past
                        if [[ "$milestone_name" != "long-term" && "$milestone_due_date" < "$(date -u +%Y-%m-%dT%H:%M:%SZ)" ]]; then
                            # Close the milestone
                            milestone_number=$(echo "$milestone" | base64 --decode | jq -r '.number')
                            curl -X PATCH -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" \
                                -d '{"state": "closed"}' \
                                "https://api.github.com/repos/SWAMP-Blimps/CatchingBlimp/milestones/$milestone_number"
                        fi
                    done
            - name: Create New Milestone
              run: |
                    # Calculate the date 2 weeks from today
                    new_milestone_date=$(date -d "+2 weeks 13:00:00 CST" +%Y-%m-%dT%H:%M:%SZ)

                    # Create the new milestone
                    new_milestone_title=$(TZ=America/New_York date -d "+2 weeks" +%m-%d-%y)
                    curl -X POST -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" \
                        -d '{"title": "'"$new_milestone_title"'", "due_on": "'"$new_milestone_date"'"}' \
                        "https://api.github.com/repos/SWAMP-Blimps/CatchingBlimp/milestones"
