name: Manual Close and Open Milestones
on:
    [push]

jobs:
    close-and-open-milestones:
        runs-on: ubuntu-latest

        steps:
        - name: Close Milestones
          uses: MrGossett/github-action-milestone-closer@v1
          env:
            GITHUB_TOKEN: ${{ secrets.RUNNER_TOKEN }}
            
        - name: Create Milestones
          uses: MrGossett/github-action-milestone-schedule@v1
          env:
            GITHUB_TOKEN: ${{ secrets.RUNNER_TOKEN }}
          with:
            recurrence: 'FREQ=WEEKLY;INTERVAL=2;BYDAY=TH;DTSTART=20240614T220000Z'
            format: '01-02-06'
            count: 1
