name: Delete Complete Milestones and Create New Milestone
on:
    [push]

jobs:
    delete-and-create-milestone:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Delete Complete Milestones
              run: |
                    # Fetch all milestones
                    milestones=$(curl -s -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" \
                        "https://api.github.com/repos/SWAMP-Blimps/CatchingBlimp/milestones?state=closed")

                    # Loop through milestones and delete fully complete ones
                    for milestone in $(echo "$milestones" | jq -r '.[] | select(.closed_issues == .open_issues) | .number'); do
                        curl -X DELETE -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" \
                            "https://api.github.com/repos/SWAMP-Blimps/CatchingBlimp/milestones/$milestone"
                    done

            - name: Create New Milestone
              run: |
                    # Calculate the date 2 weeks from today
                    new_milestone_date=$(date -d "+2 weeks 13:00:00 CST" +%Y-%m-%dT%H:%M:%SZ)

                    # Create the new milestone
                    new_milestone_title=$(date -d "+2 weeks" +%m-%d-%y)
                    curl -X POST -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" \
                        -d '{"title": "'"$new_milestone_title"'", "due_on": "'"$new_milestone_date"'"}' \
                        "https://api.github.com/repos/SWAMP-Blimps/CatchingBlimp/milestones"
