name: Manual Close and Open Milestones
on:
    [push]

jobs:
    close-and-open-milestones:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7

            - name: Close old and completed milestones
              run: | 
                    curl -X PATCH \
                        -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/SWAMP-Blimps/CatchingBlimp/milestones?state=all \
                        -d '{"state": "closed"}'

            - name: Open new milestone
              run: |
                    curl -X POST \
                        -H "Authorization: token ${{ secrets.RUNNER_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        https://api.github.com/repos/SWAMP-Blimps/CatchingBlimp/milestones \
                        -d '{"title": "New Milestone", "state": "open", "due_on": "$(date -v+2w -u +%Y-%m-%dT%H:%M:%SZ)"}'
